### ISSUE TITLE
Extension doesn't work when "ignore whitespaces" at pull request screen is on

### ISSUE THREAD

**Issue by renatoch** [reywood/bitbucket-pr-review#11]
I use a lot the ignore whitespaces option (add "?w=1" to PR url - eg: /difff?w=1), but when I do this, pr review extension stops working.
I believe there may be a url filter on the extension preventing this.
Is it possible to fix this?
Thanks!

**Comment by renatoch** [comment]
My mistake: the extension does work. What doesn't work is right after switching to "ignore whitespace" using the interface button, as it doesn't reload the page, only refreshes it, and it ends up removing the extended controls of the extesion.

**Comment by reywood** [comment]
Thanks for letting me know. I'll take a look when I get a chance.

**Comment by Toltar** [comment]
Hi, just wanted to say I am experiencing this issue as well. Any updates on this @reywood ?

**Comment by reywood** [comment]
I've been playing around with this, and I've fixed the disappearing button problem. However, there's a gotcha when using the ignore whitespace feature. This extension creates a hash of the file changes that appear in the displayed diff when a file is marked as reviewed. Since turning on the ignore whitespace feature alters the changes in the displayed diff, the file's hash will be different and the file will no longer appear to be marked as reviewed. If you turn off the ignore whitespace feature, the file will once again appear to be marked as reviewed. I'll release a new version with my changes, but wanted you to be aware of this behavior.

**Comment by renatoch** [comment]
Great @reywood , thanks! I'll work with this and let you know my findings.
Cheers

**Comment by Toltar** [comment]
Thanks, @reywood for this. This is working perfectly.
